USE [master]
GO

/****** Object:  Database [Curriculum]    Script Date: 11/04/2018 17:37:55 ******/
CREATE DATABASE [Curriculum]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Curriculum', FILENAME = N'C:\MyBasis\Curriculum.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Curriculum_log', FILENAME = N'C:\MyBasis\Curriculum_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Curriculum] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Curriculum].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Curriculum] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Curriculum] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Curriculum] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Curriculum] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Curriculum] SET ARITHABORT OFF 
GO

ALTER DATABASE [Curriculum] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Curriculum] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Curriculum] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Curriculum] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Curriculum] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Curriculum] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Curriculum] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Curriculum] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Curriculum] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Curriculum] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Curriculum] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Curriculum] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Curriculum] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Curriculum] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Curriculum] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Curriculum] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Curriculum] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Curriculum] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Curriculum] SET RECOVERY FULL 
GO

ALTER DATABASE [Curriculum] SET  MULTI_USER 
GO

ALTER DATABASE [Curriculum] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Curriculum] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Curriculum] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Curriculum] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Curriculum] SET  READ_WRITE 
GO


